# Generated by Django 5.2.6 on 2025-09-26 19:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255, verbose_name='symbol')),
                ('company_name', models.CharField(max_length=255, verbose_name='company_name')),
                ('fiscal_year', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='fiscal_year')),
                ('meeting_date', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='meeting_date')),
                ('number_of_shares', models.PositiveBigIntegerField(verbose_name='number_of_shares')),
                ('capital', models.PositiveBigIntegerField(verbose_name='capital')),
                ('eps', models.PositiveIntegerField(verbose_name='eps')),
                ('dps', models.PositiveIntegerField(verbose_name='dps')),
                ('total_dividend', models.PositiveBigIntegerField(verbose_name='total_dividend')),
                ('payment_schedule', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='payment_schedule')),
                ('comments', models.TextField(blank=True, verbose_name='comments')),
                ('latest_actual_payment_date', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='latest_actual_payment_date')),
                ('latest_payment_amount', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='latest_payment_amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='dividends', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_dividends', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
        ),
    ]
